### ISSUE TITLE
New Feature:  Choose which stats to display

### ISSUE THREAD

**Issue by iinsertNameHere** [iinsertNameHere/catnip#6]
Make it possible for the user to choose which stats to display:

> *Everything that is commented should not be displayed.*
```toml
[stats]
username = {icon = "> ", name = "user", color = "(RD)"}
hostname = {icon = "> ", name = "hname", color = "(YW)"}
uptime   = {icon = "> ", name = "uptime", color = "(BE)"}
distro   = {icon = "> ", name = "distro", color = "(GN)"}
# kernel   = {icon = "> ", name = "kernel", color = "(MA)"}
desktop  = {icon = "> ", name = "desktp", color = "(CN)"}
shell    = {icon = "> ", name = "shell", color = "(RD)"}
# colors   = {icon = "> ", name = "colors", color = "!DT!", symbol = "#"}
```
